name: medipal
description: A healthcare app with AI-powered features
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  # UI and Design
  material_color_utilities: ^0.11.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

  # State Management
  provider: ^6.1.2

  # Network and API
  http: ^1.2.1
  dio: ^5.4.2+1

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5

  share_plus: ^9.0.0
  path_provider: ^2.1.3
  gpt_markdown: ^0.1.15
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  crypto: ^3.0.5
  pin_code_fields: ^8.0.1
  device_info_plus: ^10.1.2
  url_launcher: ^6.3.2
  geolocator: ^12.0.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  health: ^11.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
